### PR TITLE
update compat

### PR DESCRIPTION
**Pull request by oscardssmith**

### CODE REVIEW

**Comment by BioTurboNick** [comment]
@tkf Can this be merged?

**Comment by chriselrod** [comment]
@tkf bump?

**Comment by oscardssmith** [comment]
@DilumAluthge bump?

**Comment by DilumAluthge** [comment]
I don't have the commit bit here, but I'll try to ping @tkf on Slack.

**Comment by tkf** [comment]
Sorry I'm late to review this. Releasing: https://github.com/JuliaRegistries/General/pull/68628

**Pull request merged**
